### ISSUE TITLE
Rack Timeout support

### ISSUE THREAD

**Issue by matthewford** [roidrage/lograge#186]
Hello I'm seeing this error:

```
Could not log "process_action.action_controller" event. NoMethodError: undefined method `[]' for #<ActiveSupport::Notifications::Event:0x007f4b81928910> ["/home/vcap/app/config/environments/production.rb:55:in `block (3 levels) in <top (required)>'", "/home/vcap/app/config/environments/production.rb:54:in `any?'", "/home/vcap/app/config/environments/production.rb:54:in `block (2 levels) in <top (required)>'", "/home/vcap/app/vendor/bundle/ruby/2.3.0/gems/lograge-0.3.6/lib/lograge.rb:83:in `block in ignore?'", "/home/vcap/app/vendor/bundle/ruby/2.3.0/gems/lograge-0.3.6/lib/lograge.rb:83:in `any?'", "/home/vcap/app/vendor/bundle/ruby/2.3.0/gems/lograge-0.3.6/lib/lograge.rb:83:in `ignore?'", "/home/vcap/app/vendor/bundle/ruby/2.3.0/gems/lograge-0.3.6/lib/lograge/log_subscriber.rb:9:in `process_action'", "/home/vcap/app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.5.2/lib/active_support/subscriber.rb:100:in `finish'", "
```

I suspect its to do with the request timing out, as we have rack timeout installed, I see there was a similar issue, https://github.com/roidrage/lograge/pull/134/files any ideas on how to get this working with Rack Timeout?

**Comment by benlovell** [comment]
Hey @matthewford. If you could provide a sample app / failing spec that demonstrates the problem I'd be happy to resolve this for you.
