### ISSUE TITLE
undefined method `lograge` when using lograge.rb initializer

### ISSUE THREAD

**Issue by belgoros** [roidrage/lograge#253]
I followed the [steps](https://github.com/roidrage/lograge#installation) to setup the lograge and created `lograge.rb` initializer as follows:
```
# initializers/lograge.rb

Rails.application.configure do
  config.lograge.base_controller_class = 'ActionController::API'
  config.lograge.formatter = Lograge::Formatters::Logstash.new
  config.lograge.logger = LogStashLogger.new(type: :udp, host: ENV['logstash_host'], port: ENV['logstash_port'])
end
``` 
Then I put the following option into `production` and `staging` environment files:
```
# environments/staging.rb, production.rb

config.lograge.enabled = true
```
When starting the Rails server in `development` mode I'm getting the following error:
```
=> Booting Puma
=> Rails 5.2.0 application starting in development 
=> Run `rails server -h` for more startup options
Exiting
Traceback (most recent call last):
	61: from bin/rails:4:in `<main>'
	60: from bin/rails:4:in `require'
...
10: from /Users/Serguei/.rvm/gems/ruby-2.5.0/gems/activesupport-5.2.0/lib/active_support/notifications.rb:170:in `instrument'
	 9: from /Users/Serguei/.rvm/gems/ruby-2.5.0/gems/railties-5.2.0/lib/rails/engine.rb:657:in `block in load_config_initializer'
	 8: from /Users/Serguei/.rvm/gems/ruby-2.5.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:277:in `load'
	 7: from /Users/Serguei/.rvm/gems/ruby-2.5.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:249:in `load_dependency'
	 6: from /Users/Serguei/.rvm/gems/ruby-2.5.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:277:in `block in load'
	 5: from /Users/Serguei/.rvm/gems/ruby-2.5.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:277:in `load'
	 4: from /Users/Serguei/projects/decastore/decastore-api/config/initializers/lograge.rb:1:in `<top (required)>'
	 3: from /Users/Serguei/.rvm/gems/ruby-2.5.0/gems/railties-5.2.0/lib/rails/railtie.rb:216:in `configure'
	 2: from /Users/Serguei/.rvm/gems/ruby-2.5.0/gems/railties-5.2.0/lib/rails/railtie.rb:216:in `instance_eval'
	 1: from /Users/Serguei/projects/decastore/decastore-api/config/initializers/lograge.rb:2:in `block in <top (required)>'
/Users/Serguei/.rvm/gems/ruby-2.5.0/gems/railties-5.2.0/lib/rails/railtie/configuration.rb:97:in `method_missing': undefined method `lograge' for #<Rails::Application::Configuration:0x00007fbe47b1ceb8> (NoMethodError)
```
What's wrong with that ?
I'm using:
```
rails 5.2.0
ruby 2.5.0
lograge 0.10.0
```
Thank you.

**Comment by benlovell** [comment]
You've declared the `lograge` dependency in the `staging` and `production` gem groups I assume. You can fix this by declaring the gem dependency outside of those groups or moving the configuration code out of the initializer and into the `staging.rb` and/or `production.rb`.

**Comment by belgoros** [comment]
Ah, mu bad, got it. Thank you.
