### ISSUE TITLE
TypeError: no implicit conversion of String into Integer when adding lograge to Rails project with Rack 3.0.9 and Puma 6.4.2

### ISSUE THREAD

**Issue by erik-brueggemann** [roidrage/lograge#387]
### Environment
- **Rails version**: 7.2-alpha (latest commit as of issue)
- **Rack version**: 3.0.9
- **Puma version**: 6.4.2
- **Ruby version**: 3.3.0
- **Lograge version**: 0.14 / main (latest commit as of issue)

### Description
After adding `lograge` to a new Rails project's Gemfile, starting the server results in a `TypeError` with the message "no implicit conversion of String into Integer". This issue prevents the server from starting and appears to be related to middleware stack execution, specifically Rack's request handling.

### Steps to Reproduce
1. Create a new Rails project with the specified environment versions.
2. Add `lograge` to the Gemfile and bundle install.
3. Add documented `lograge.rb` to `initializers`
4. Attempt to start the Rails server.

```sh
# `rails new` flags used
--main -d postgresql --skip-action-mailbox --skip-action-text --skip-action-cable --skip-jbuilder -a propshaft -c tailwind --skip-test --skip-system-test
```

```rb
#lograge.rb 

Rails.application.configure do
  config.lograge.enabled = true
end
```

### Expected Behavior
The Rails server starts without errors, and `lograge` successfully initializes.

### Actual Behavior
The server startup fails with the following exception trace (paths anonymized):

```
Puma caught this error: no implicit conversion of String into Integer (TypeError)
[...]/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/rack-3.0.9/lib/rack/request.rb:101:in `[]'
[...]/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/rack-3.0.9/lib/rack/request.rb:101:in `get_header'
[...]/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/bundler/gems/rails-1a92af2b5140/actionpack/lib/action_dispatch/middleware/show_exceptions.rb:35:in `rescue in call'
[...]/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/bundler/gems/rails-1a92af2b5140/actionpack/lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
[...]/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/bundler/gems/lograge-2839d2c7786b/lib/lograge/rails_ext/rack/logger.rb:18:in `call_app'
[...]/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/bundler/gems/rails-1a92af2b5140/railties/lib/rails/rack/logger.rb:28:in `call'
[...]/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/bundler/gems/rails-1a92af2b5140/actionpack/lib/action_dispatch/middleware/remote_ip.rb:96:in `call'
[...]/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/request_store-1.6.0/lib/request_store/middleware.rb:19:in `call'
[...]/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/bundler/gems/rails-1a92af2b5140/actionpack/lib/action_dispatch/middleware/request_id.rb:33:in `call'
[...]/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/rack-3.0.9/lib/rack/method_override.rb:28:in `call'
[...]/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/rack-3.0.9/lib/rack/runtime.rb:24:in `call'
[...]/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/bundler/gems/rails-1a92af2b5140/activesupport/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
[...]/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/bundler/gems/rails-1a92af2b5140/actionpack/lib/action_dispatch/middleware/server_timing.rb:61:in `block in call'
[...]/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/bundler/gems/rails-1a92af2b5140/actionpack/lib/action_dispatch/middleware/server_timing.rb:26:in `collect_events'
[...]/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/bundler/gems/rails-1a92af2b5140/actionpack/lib/action_dispatch/middleware/server_timing.rb:60:in `call'
[...]/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/bundler/gems/rails-1a92af2b5140/actionpack/lib/action_dispatch/middleware/executor.rb:16:in `call'
[...]/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/bundler/gems/rails-1a92af2b5140/actionpack/lib/action_dispatch/middleware/static.rb:27:in `call'
[...]/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/rack-3.0.9/lib/rack/sendfile.rb:114:in `call'
[...]/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/bundler/gems/rails-1a92af2b5140/actionpack/lib/action_dispatch/middleware/host_authorization.rb:143:in `call'
[...]/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/bundler/gems/rails-1a92af2b5140/railties/lib/rails/engine.rb:536:in `call'
[...]/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/puma-6.4.2/lib/puma/configuration.rb:272:in `call'
[...]/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/puma-6.4.2/lib/puma/request.rb:100:in `block in handle_request'
[...]/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/puma-6.4.2/lib/puma/thread_pool.rb:378:in `with_force_shutdown'
[...]/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/puma-6.4.2/lib/puma/request.rb:99:in `handle_request'
[...]/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/puma-6.4.2/lib/puma/server.rb:464:in `process_client'
[...]/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/puma-6.4.2/lib/puma/server.rb:245:in `block in run'
[...]/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/puma-6.4.2/lib/puma/thread_pool.rb:155:in `block in spawn_thread'
```

**Comment by luizkowalski** [comment]
More info: https://github.com/rails/rails/issues/51041

**Comment by ghiculescu** [comment]
https://github.com/rails/rails/pull/51053

**Comment by erik-brueggemann** [comment]
With the recent PR on Rails closed (https://github.com/rails/rails/commit/9e01d93547e2082e2e88472748baa0f9ea63c181), lograge works again as expected. Thank you @ghiculescu !
