### ISSUE TITLE
Cannot dump log for ActionDispatch::Http::UploadedFile in JSON format

### ISSUE THREAD

**Issue by kidlab** [roidrage/lograge#92]
I am using lograge with this configuration:
```ruby
config.lograge.formatter = Lograge::Formatters::Json.new
config.lograge.enabled = true

config.lograge.custom_options = lambda do |event|
  {
    time: event.time,
    user_agent: event.payload[:user_agent],
    authorization: event.payload[:authorization],
    params: event.payload[:params]
  }
end
```
And it raised this error when there was photo uploading:

```
Could not log "process_action.action_controller" event. EncodingError: Invalid Unicode
 ["/data/ruby-2.0.0-p594/gems/lograge-0.3.0/lib/lograge/formatters/json.rb:6:in `dump'", "/data/ruby-2.0.0-p594/gems/lograge-0.3.0/lib/lograge/formatters/json.rb:6:in `call'", ...]
```
I think it is because it could not dump `ActionDispatch::Http::UploadedFile`. Any thought?

**Comment by sparksp** [comment]
I just solved this myself by calling `as_json(except: ["tempfile"])` on the params.

```ruby
config.lograge.custom_options = lambda do |event|
  {
    params: event.payload[:params].as_json(except: ["tempfile"])
  }
end
```

**Comment by myriky** [comment]
i've solved. the problem is ActionDispatch::Http::UploadedFile dump is too verbose.
just pick want you to see. i just picked "Header" cuz which contains whole information uploaded file.

**here is ActionDispatch::Http::UploadedFile model**
```
{"file"=>#<ActionDispatch::Http::UploadedFile:0x007f7f7abf8050 @tempfile=#<Tempfile:/var/folders/ml/s691k8ls7f3568nh2yw_nm9c0000gn/T/RackMultipart20170913-64272-11xee7s.png>, @original_filename="스크린샷 2017-09-08 오후 3.11.12.png", @content_type="image/png", @headers="Content-Disposition: form-data; name=\"file\"; filename=\"\xE1\x84\x89\xE1\x85\xB3\xE1\x84\x8F\xE1\x85\xB3\xE1\x84\x85\xE1\x85\xB5\xE1\x86\xAB\xE1\x84\x89\xE1\x85\xA3\xE1\x86\xBA 2017-09-08 \xE1\x84\x8B\xE1\x85\xA9\xE1\x84\x92\xE1\x85\xAE 3.11.12.png\"\r\nContent-Type: image/png\r\n">, "format"=>:json, "controller"=>"api/v1/uploads", "action"=>"create"}
```

it's too verbose to logging.
it might be fine to pick @headers value.

**monkey patch for UploadedFile** 
```
class ActionDispatch::Http::UploadedFile
  def as_json(options = nil)
    %w(headers).inject({}) do |hash, attr|
      hash[attr] = send(attr).force_encoding('utf-8')
      hash
    end
  end
end
```

**config/application.rb**
```
config.lograge.custom_options = lambda do |event|
      exceptions = %w(controller action format)
      {params: event.payload[:params].as_json(except: exceptions)}
end
```

**before uploadedFile dump**
```
{"file"=>#<ActionDispatch::Http::UploadedFile:0x007f7f7abf8050 @tempfile=#<Tempfile:/var/folders/ml/s691k8ls7f3568nh2yw_nm9c0000gn/T/RackMultipart20170913-64272-11xee7s.png>, @original_filename="스크린샷 2017-09-08 오후 3.11.12.png", @content_type="image/png", @headers="Content-Disposition: form-data; name=\"file\"; filename=\"\xE1\x84\x89\xE1\x85\xB3\xE1\x84\x8F\xE1\x85\xB3\xE1\x84\x85\xE1\x85\xB5\xE1\x86\xAB\xE1\x84\x89\xE1\x85\xA3\xE1\x86\xBA 2017-09-08 \xE1\x84\x8B\xE1\x85\xA9\xE1\x84\x92\xE1\x85\xAE 3.11.12.png\"\r\nContent-Type: image/png\r\n">, "format"=>:json, "controller"=>"api/v1/uploads", "action"=>"create"}
```
**lodrage doesn't work**
```
Could not log "process_action.action_controller" event. Encoding::UndefinedConversionError: "\x89" from ASCII-8BIT to UTF-8 
```

**after uploadedFile dump**
```
{"files"=>[{"headers"=>"Content-Disposition: form-data; name=\"files[]\"; filename=\"스크린샷 2017-09-08 오후 3.11.12.png\"\r\nContent-Type: image/png\r\n"}], "format"=>"json", "controller"=>"api/v1/uploads", "action"=>"create"}
```
**lodrage it works!**
```
"params":{"file":{"content_type":"image/png","headers":"Content-Disposition: form-data; name=\"file\"; filename=\"스크린샷 2017-09-08 오후 3.11.12.png\"\r\nContent-Type: image/png\r\n"
```
