### ISSUE TITLE
puma-production undefined method

### ISSUE THREAD

**Issue by mirzali** [roidrage/lograge#98]
I'm running a puma server for my production setup. However I cannot integrate the lograge because of the following error.

I'm not doing anything special so I'm just including config.lograge.enabled = true in production.rb and thats it.

I wonder if someone else has encountered such a issue.

```
/usr/local/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/railties-4.2.0/lib/rails/railtie/configuration.rb:95:in `method_missing': undefined method `lograge' for #<Rails::Application::Configuration:0x007fb696924470> (NoMethodError)
        from /home/deployer/apps/ren/releases/20150106184201/config/environments/production.rb:89:in `block in <top (required)>'
        from /usr/local/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/railties-4.2.0/lib/rails/railtie.rb:210:in `instance_eval'
        from /usr/local/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/railties-4.2.0/lib/rails/railtie.rb:210:in `configure'
        from /usr/local/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/railties-4.2.0/lib/rails/railtie.rb:182:in `configure'
        from /home/deployer/apps/ren/releases/20150106184201/config/environments/production.rb:1:in `<top (required)>'
        from /usr/local/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
        from /usr/local/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `block in require'
        from /usr/local/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:240:in `load_dependency'
        from /usr/local/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
        from /usr/local/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/railties-4.2.0/lib/rails/engine.rb:598:in `block (2 levels) in <class:Engine>'
        from /usr/local/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/railties-4.2.0/lib/rails/engine.rb:597:in `each'
        from /usr/local/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/railties-4.2.0/lib/rails/engine.rb:597:in `block in <class:Engine>'
        from /usr/local/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/railties-4.2.0/lib/rails/initializable.rb:30:in `instance_exec'
        from /usr/local/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/railties-4.2.0/lib/rails/initializable.rb:30:in `run'
        from /usr/local/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/railties-4.2.0/lib/rails/initializable.rb:55:in `block in run_initializers'
        from /usr/local/rbenv/versions/2.1.5/lib/ruby/2.1.0/tsort.rb:226:in `block in tsort_each'
        from /usr/local/rbenv/versions/2.1.5/lib/ruby/2.1.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
        from /usr/local/rbenv/versions/2.1.5/lib/ruby/2.1.0/tsort.rb:418:in `block (2 levels) in each_strongly_connected_component_from'
        from /usr/local/rbenv/versions/2.1.5/lib/ruby/2.1.0/tsort.rb:427:in `each_strongly_connected_component_from'
        from /usr/local/rbenv/versions/2.1.5/lib/ruby/2.1.0/tsort.rb:417:in `block in each_strongly_connected_component_from'
        from /usr/local/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/railties-4.2.0/lib/rails/initializable.rb:44:in `each'
        from /usr/local/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/railties-4.2.0/lib/rails/initializable.rb:44:in `tsort_each_child'
        from /usr/local/rbenv/versions/2.1.5/lib/ruby/2.1.0/tsort.rb:411:in `call'
        from /usr/local/rbenv/versions/2.1.5/lib/ruby/2.1.0/tsort.rb:411:in `each_strongly_connected_component_from'
        from /usr/local/rbenv/versions/2.1.5/lib/ruby/2.1.0/tsort.rb:347:in `block in each_strongly_connected_component'
        from /usr/local/rbenv/versions/2.1.5/lib/ruby/2.1.0/tsort.rb:345:in `each'
        from /usr/local/rbenv/versions/2.1.5/lib/ruby/2.1.0/tsort.rb:345:in `call'
        from /usr/local/rbenv/versions/2.1.5/lib/ruby/2.1.0/tsort.rb:345:in `each_strongly_connected_component'
        from /usr/local/rbenv/versions/2.1.5/lib/ruby/2.1.0/tsort.rb:224:in `tsort_each'
        from /usr/local/rbenv/versions/2.1.5/lib/ruby/2.1.0/tsort.rb:205:in `tsort_each'
        from /usr/local/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/railties-4.2.0/lib/rails/initializable.rb:54:in `run_initializers'
        from /usr/local/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/railties-4.2.0/lib/rails/application.rb:352:in `initialize!'
        from /usr/local/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/railties-4.2.0/lib/rails/railtie.rb:194:in `public_send'
        from /usr/local/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/railties-4.2.0/lib/rails/railtie.rb:194:in `method_missing'
        from /home/deployer/apps/ren/current/config/environment.rb:5:in `<top (required)>'
        from /home/deployer/apps/ren/current/config.ru:3:in `require'
        from /home/deployer/apps/ren/current/config.ru:3:in `block in <main>'
        from /usr/local/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rack-1.6.0/lib/rack/builder.rb:55:in `instance_eval'
        from /usr/local/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rack-1.6.0/lib/rack/builder.rb:55:in `initialize'
        from /home/deployer/apps/ren/current/config.ru:in `new'
        from /home/deployer/apps/ren/current/config.ru:in `<main>'
        from /usr/local/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rack-1.6.0/lib/rack/builder.rb:49:in `eval'
        from /usr/local/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rack-1.6.0/lib/rack/builder.rb:49:in `new_from_string'
        from /usr/local/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rack-1.6.0/lib/rack/builder.rb:40:in `parse_file'
        from /usr/local/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/puma-2.10.2/lib/puma/configuration.rb:99:in `app'
        from /usr/local/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/puma-2.10.2/lib/puma/runner.rb:123:in `app'
        from /usr/local/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/puma-2.10.2/lib/puma/runner.rb:130:in `start_server'
        from /usr/local/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/puma-2.10.2/lib/puma/cluster.rb:207:in `worker'
        from /usr/local/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/puma-2.10.2/lib/puma/cluster.rb:106:in `block (2 levels) in spawn_workers'
        from /usr/local/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/puma-2.10.2/lib/puma/cluster.rb:106:in `fork'
        from /usr/local/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/puma-2.10.2/lib/puma/cluster.rb:106:in `block in spawn_workers'
        from /usr/local/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/puma-2.10.2/lib/puma/cluster.rb:103:in `times'
        from /usr/local/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/puma-2.10.2/lib/puma/cluster.rb:103:in `spawn_workers'
        from /usr/local/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/puma-2.10.2/lib/puma/cluster.rb:154:in `check_workers'
        from /usr/local/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/puma-2.10.2/lib/puma/cluster.rb:408:in `run'
        from /usr/local/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/puma-2.10.2/lib/puma/cli.rb:507:in `run'
        from /usr/local/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/puma-2.10.2/lib/puma/control_cli.rb:248:in `start'
        from /usr/local/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/puma-2.10.2/lib/puma/control_cli.rb:216:in `run'
        from /usr/local/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/puma-2.10.2/bin/pumactl:8:in `<top (required)>'
        from /usr/local/rbenv/versions/2.1.5/bin/pumactl:23:in `load'
        from /usr/local/rbenv/versions/2.1.5/bin/pumactl:23:in `<main>'
```

**Comment by mirzali** [comment]
I reinstalled the server and it runs ok now. I wonder what it was though.

**Comment by pxlpnk** [comment]
This looks to me like lograge was not properly installed. Did you have lograge in a group within your Gemfile?

**Comment by mirzali** [comment]
it was just gem 'lograge' without any group

**Comment by pxlpnk** [comment]
Then I have no idea what this could have been, maybe a glitch in the space time continuum.

Can we close this or you want to investigate further?

**Comment by benlovell** [comment]
That pesky space time continuum, always messing with our softwares!

**Comment by foton** [comment]
This things happen to me to (now). One project was ok, another not. I fixed it by putting `require "lograge"` on top of file where I am calling `config.lograge.enabled = true`
